version: '3.8'

services:
  tf:
    build: ./tf
    container_name: tf
    tty: true
    volumes:
      - ./:/workspace:cached
  pg:
    image: postgres:9.5.23
    expose:
      - '5432'
    ports:
      - '54325:5432'
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_DB=cyberpunk202x
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DaVinci
