version: '3.8'

services:
  tf:
    build: ./tf
    container_name: tf
    tty: true
    volumes:
      - ./:/workspace:cached
  pg:
    image: postgres:9.5.23
    expose:
      - '5432'
    ports:
      - '54325:5432'
      # Optionally also fwd mac host port 5432 to docker.
      # This is useful if you want DaVinci to be able to connect to the local
      # docker pg db.
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_DB=cyberpunk202x
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DaVinci
