version: '3.3'

services:
  sq_pg:
    container_name: sq_pg
    image: postgres:9.5.23
    expose:
      - '5432'
    ports:
      - '54325:5432'
      # Optionally also fwd mac host port 5432 to docker.
      # This is useful if you want DaVinci to be able to connect to the local
      # docker pg db.
      - '5432:5432'
    restart: always
    volumes:
      - /opt/ebs:/opt/ebs:cached
      # /host/path:/container/path
    environment:
      - POSTGRES_DB=cyberpunk202x
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DaVinci
      - PGDATA=/opt/ebs/pgdata
  sq_tf:
    container_name: sq_tf
    build: ./tf
    tty: true
    volumes:
      - ./:/workspace:cached
    links:
      - sq_pg
    environment:
      POSTGRES_DB: 'cyberpunk202x'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'DaVinci'
      PG: 'postgres://postgres:DaVinci@sq_pg/cyberpunk202x'
